# Sử dụng image Odoo 16 làm nền tảng
FROM odoo:16

# Cài đặt các gói cần thiết để xây dựng Python 3.10
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    nodejs \
    npm \
    libxml2-dev \
    libxslt1-dev \
    libjpeg-dev \
    libldap2-dev \
    libsasl2-dev \
    libpq-dev \
    build-essential \
    wget \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-venv \
    fonts-liberation \
    libfreetype6 \
    libfontconfig1 \
    xfonts-75dpi \
    xfonts-base \
    zlib1g-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    && rm -rf /var/lib/apt/lists/*

# Install wkhtmltopdf
RUN wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_amd64.deb && \
    dpkg -i wkhtmltox_0.12.6.1-2.bullseye_amd64.deb || true && \
    apt-get -f install -y && \
    rm wkhtmltox_0.12.6.1-2.bullseye_amd64.deb

# Tải và cài đặt Python 3.10
RUN wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz && \
    tar xzf Python-3.10.0.tgz && \
    cd Python-3.10.0 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.10.0 Python-3.10.0.tgz

# Đặt Python 3.10 làm phiên bản Python mặc định
RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.10 1 && \
    update-alternatives --set python3 /usr/local/bin/python3.10


#ENV PATH="/usr/local/bin:$PATH"
#ENV PYTHONPATH="/usr/local/lib/python3.10/site-packages"
#RUN ln -sf /usr/local/bin/python3.10 /usr/bin/python3

# Cài đặt pip cho Python 3.10
RUN wget https://bootstrap.pypa.io/get-pip.py && \
    python3.10 get-pip.py && \
    rm get-pip.py

# Cài đặt các gói Python cần thiết cho Odoo bằng Python 3.10
COPY requirements.txt /tmp/requirements.txt
RUN pip3.10 install -r /tmp/requirements.txt
RUN pip3 install --no-cache-dir \
    Babel==2.9.1 \
    chardet==3.0.4 \
    decorator==4.4.2 \
    docutils==0.16 \
    ebaysdk==2.1.5 \
    freezegun==0.3.15 \
    gevent==22.10.2 \
    greenlet==2.0.2 \
    idna==2.8 \
    Jinja2==3.1.2 \
    libsass==0.22.0 \
    lxml==4.9.1 \
    MarkupSafe==2.1.1 \
    num2words==0.5.12 \
    ofxparse==0.19 \
    passlib==1.7.4 \
    Pillow==9.3.0 \
    polib==1.1.1 \
    psutil==5.9.4 \
    psycopg2==2.9.5 \
    pydot==1.4.2 \
    python-dateutil==2.8.2 \
    python-ldap==3.4.3 \
    python-stdnum==1.18 \
    pytz==2022.6 \
    pyusb==1.2.1 \
    qrcode==7.4.2 \
    reportlab==3.6.12 \
    requests==2.28.1 \
    urllib3==1.26.13 \
    vobject==0.9.6.1 \
    Werkzeug==2.2.3 \
    xlrd==1.2.0 \
    XlsxWriter==3.0.3 \
    xlwt==1.3.0 \
    zeep==4.2.1 \
    PyPDF2==2.12.1 \
    rasterstats \
    pandas \
    shapely \
    html2text \
    psycopg2-binary

# Tạo thư mục /opt/ovis nếu cần cho add-ons hoặc cấu hình sau này
# RUN mkdir -p /opt/ovis && chown -R odoo:odoo /opt/ovis

# Chạy với quyền user odoo
# USER odoo