[options]
addons_path = /opt/bitnami/odoo/addons,/opt/bitnami/odoo/odoo/addons,/opt/avis16/addons-sud,/opt/avis16/addons-sud/base_restapi,/opt/avis16/tools,/opt/avis16/india_sucden,/opt/avis16/vietnam_sucden,/opt/avis16/vietnam_sucden/gg_map,/opt/avis16/vietnam_sucden/gg_map/web_view_google_map_drawing/example,/opt/avis16/ned_sucden
data_dir = /var/lib/odoo
admin_passwd = admin@ned
db_port = 5432
db_user = odoo
db_password = odoo
db_host = ovis16-db-1