# -*- coding: utf-8 -*-
{
    'name': 'Sucden INDIA Report',
    'version': '16.0',
    'category': 'SUCDEN Report Manager',
    'depends': ['sd_india_quality_control', 'sd_india_mrp','sd_india_inventory','sd_india_traffic'],
    'data': [
            'security/security.xml',
            'security/ir.model.access.csv',
            'views/production_report_view.xml',
            'views/sucden_syn_config_view.xml',
            'views/batch_report.xml',
            'views/production_analysis_view.xml',
            'views/batch_pnl_upgrade_view.xml',
            'views/input_value.xml',
            'views/output_value.xml',
            'views/faq_prod_loss_tracking.xml',
            'wizard/npe_unfixed_wizard.xml',
            'wizard/wizard_report_bag_transfer_view.xml',
            'views/npe_master.xml',
            'views/stock_intake_week.xml',
            'views/stock_intake_supplier.xml',
            'views/faq_stack_tracking.xml',
            'views/production_plan_view.xml',
            'views/shipment_quality.xml',
            'views/internal_transfer_tracking.xml',
            'views/shipment.xml',
            'views/grn_matching_report.xml',
            'views/fob_deviation.xml',
            'views/fob_weight_franchise.xml',
            'views/report_grn_unallocated.xml',
            'views/report_bag_transfer_view.xml',
            # 'views/long_short_fob_view.xml',
            # 'views/long_short_fob_v2_view.xml',
            # 'views/long_short_factory_view.xml',
            # 'views/cash_book_view.xml',
            'views/menu.xml',


            'report/report_view.xml',
            ],
    'installable': True,
    'auto_install': False,
    'author': 'Sucden Vietnam Ltd',
}