# -*- coding: utf-8 -*-
{
    'name': 'SUCDEN CONTRACT VIETNAM',
    'category': 'SUCDEN CONTRACT VIETNAM',
    'version' : '16.0.1.0',
    'author': 'SCUDEN VIETNAM',
    'website': 'https://www.sucden.com',
    'depends': ['base','sd_pur_sales', 'sd_master_vietnam', 'api_restful', 'account_debit_note'],
    'description': """
    """,
    'data': [
        'security/ir.model.access.csv',
        'wizard/wizard_create_invoice_view.xml',
        'security/request_final_payment_security.xml',
        'data/group.xml',
        'views/menu.xml',
        'views/purchase_contract_view.xml',
        'views/account_tax_view.xml',
        'views/res_company_view.xml',
        'views/account_move_view.xml',
        'views/shipping_instruction_view.xml',
        'views/diff_configuration_view.xml',
        'views/stock_allocation_view.xml',
        'views/average_price_contract_view.xml',
        'views/sale_contract_view.xml',
        'views/stock_picking_view.xml',
        'wizard/import_farmer_view.xml',
        'wizard/wizard_report_average_price.xml',
        'wizard/wizard_purchase_contract.xml',
        'wizard/wizard_reason_force_close_view.xml',
        'wizard/wizard_generate_bank_account_view.xml',
        'wizard/mapping_picking_invoice_view.xml',
        'report/report_view.xml'
    ],
    'assets': {
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}
